version: "3"
services:
  photon:
    image: ghcr.io/automattic/vip-container-images/photon:latest
    volumes:
      - photon-uploads:/usr/share/webapps/photon/uploads
      - ./photon/config.php:/usr/share/webapps/photon/config.php

  nginx:
    build: ./nginx
    ports:
      - "9090:80"
    depends_on:
      - photon
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - photon-uploads:/usr/share/webapps/photon/uploads:ro

volumes:
  photon-uploads:
